baseURL = "https://gc00.owowo.dev"
publishDir = "../public"
title = "GrassCarp_homepage"
languageCode = "en"

enableEmoji = true
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"

[params]
  favicon = "/favicon.ico"
  customCSS = ["css/custom.css"]

[params.author]
  name = "GrassCarp_"
  headline = "d--xr-xrwx"
  image = "avatar.jpg"
  links = [
    { blog = { href = "https://gc00.owowo.dev/blog", text = "Blog - nonsense"} },
    { gallery = { href = "https://gc00.owowo.dev/gallery", text = "Gallery" } },
    { email = { href = "mailto:grasscarp00@owowo.dev", text = "Email" } },
    { memos = { href = "https://memos.owowo.dev/u/grasscarp00", text = "memos (owowo)" } },
    { github = { href = "https://github.com/grasscarp00" } },
    { telegram = { href = "https://t.me/grasscarp00" } },
    { bluesky = { href = "https://grasscarp00.bsky.social/" } },
    { gpg = { href = "https://github.com/grasscarp00.gpg", text = "GPG key" } },
#    { mastodon = { href = "https://" } }
#    { discord = { href = "https://discord.com/" } },
#    { owowo = { href = "https://owowo.dev", text = "owowo.dev" } },
  ]
