mainSections = ["post"]
rssFullContent = true
favicon = "/favicon.ico"

[author]
  name = "GrassCarp_"
  email = "grasscarp00@owowo.dev"

[footer]
  since = 2025

[sidebar]
  emoji = "🌹"
  [sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"

[article]
  math = true
  toc = true
  readingTime = true
  [article.license]
    enabled = true

[widgets]
  [[widgets.homepage]]
    type = "search"
  [[widgets.homepage]]
    type = "archives"
    [widgets.homepage.params]
      limit = 5
  [[widgets.homepage]]
    type = "categories"
  [[widgets.homepage]]
    type = "tag-cloud"
    [widgets.homepage.params]
      limit = 10
  [[widgets.page]]
    type = "toc"

[defaultImage]
  enabled = true
  local = true
  src = "img/default.jpg"

[colorScheme]
  toggle = true
  default = "auto"

[imageProcessing]
  cover.enabled = true
  content.enabled = true
